### PR TITLE
Create dependency-review.yml

### PR DESCRIPTION
**Pull request by jeffpaul**
### Description of the Change

Adds a [dependency review action](https://github.com/actions/dependency-review-action) that scans all PRs for introducing insecure dependencies and will block merge of those PRs until the insecure item is resolved.  Will help protect us from accidentally introducing insecure code into our projects.  More details on this official GitHub Action here: https://github.blog/changelog/2022-04-06-github-action-for-dependency-review-enforcement/.

### Alternate Designs

Don't have this and just... 🤞🏼?

### Possible Drawbacks

none identified

### Verification Process

Already verified as working in https://github.com/10up/distributor/pull/869, merely replicating that change in this repo.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

> Added - Dependency security scanning.

### Credits

Props @jeffpaul.

### CODE REVIEW

**Comment by jeffpaul** [comment]
Hi there @tealchutton, not sure how you snuck into the @10up/open-source-practice team but I'm going to remove your review on this PR and add someone from the Open Source Practice instead.

**Review by peterwilsoncc — APPROVED** [review]
LGTM, verified against documentation.

**Comment by peterwilsoncc** [comment]
Test / WPA action has been failing for a little while in trunk, I think this is safe to merge.

**Comment by jeffpaul** [comment]
Yeah, WP Acceptance should get removed and replaced with our Cypress e2e tests

**Pull request merged**
