### PR TITLE
Add: service provider request response info to Site Health Info screen

### LINKED ISSUE #143: Add service provider request response info to Site Health Info screen
**Is your enhancement related to a problem? Please describe.**
Building on the work in #108, let's add the results of the most recent request to each provider as this will likely help when troubleshooting service provider-related issues.

**Describe the solution you'd like**
- [ ] store latest request response per service provider in options
- [ ] translate request response into human-ish terms in Site Health Info screen

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change
Add new latest response line to each service provider in Site Health > Info > ClassifAI.

### Alternate Designs
n/a

### Benefits
Show the results of the most recent request to each provider as this will likely help when troubleshooting service provider-related issues.

### Possible Drawbacks
n/a

### Verification Process
0. Go to Tools > Site Health > Info > ClassifAI.
1. See Latest response shows `N/A`.
2. With Watson NLU enabled, update a post.
3. With Computer Vision enabled, upload an image.
4. Go to Tools > Site Health > Info > ClassifAI.
5. See the latest responses with data.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/classifai/blob/develop/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues
Closes #143 

### Changelog Entry

Added: Result of the latest request of all providers to Site Health.

### CODE REVIEW

**Comment by johnwatkins0** [comment]
@dinhtungdu This is looking great, and worked as expected in my test environment. 

One thing: Do you think we should merge #149 ahead of this and update this PR for the new Smart Cropping request that update introduces? Would just want to confirm with @jeffpaul that we're good to merge that PR, and someone would need to 👍 it.

Alternatively, we could merge this first and I could update #149 to handle the info from that request 😸

**Comment by dinhtungdu** [comment]
> Do you think we should merge #149 ahead of this and update this PR for the new Smart Cropping request that PR introduces?

Yes, I think so too.

**Comment by jeffpaul** [comment]
Agreed here as well.

**Comment by jeffpaul** [comment]
@dinhtungdu #149 has been merged, so this PR can be updated for the new Smart Cropping request.

**Comment by dinhtungdu** [comment]
@jeffpaul @johnwatkins0 I added smart cropping response, this PR is ready to review.

**Comment by jeffpaul** [comment]
@dinhtungdu looks like GitHub had some networking issues as this got merged.  Could you double check `develop` to ensure it's got your changes from this PR as expected?

**Pull request merged**
