### PR TITLE
Fix: Smart cropping results not as expected

### LINKED ISSUE #224: Smart cropping results not as expected
**Describe the bug**
I've tested ClassifAI 1.5.1 on WordPress 5.5.1, 5.4, and 5.3 and am seeing that image tags and alt text work as expected (yay!) but the smart cropping feature isn't providing the desired result (boo!).

**Steps to Reproduce**

1. Upload an image to the media library, example:
dog-on-red-background
2. See that cropped thumbnail only captures the top of the dog:
bad-crop-result
3. Click "edit" to see that alt text and image tags worked as expected.

**Expected behavior**
Resulting crop would more closely match what [Azure Computer Vision](https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/#features) demonstrates on their site:
azure-result

**Screenshots**
See in-line in this issue.

**Environment information**
 - Device: Mac mini (2018)
 - OS: macOS 10.15.6
 - Browser and version: Firefox 80.0.1 (64-bit)
 - WordPress version: 5.5.1, 5.4, and 5.3 tested
 - ClassifAI 1.5.1

ClassifAI image processing settings:
classifai-image-settings

**Additional context**

I'll try and dig up the Azure API docs to see if something changed since our original implementation, but open to other triaging to help on this.

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change
This PR changes the value of `smartCropping` parameter (in the URL) from `1` to `true`. The Azure API doesn't accept `1` as boolean value.

### Verification Process
Note that the example image in #224 doesn't work well, see [the screenshot](https://prnt.sc/uwbt4i). Please test with other images.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues
Close #224

### CODE REVIEW

**Comment by oscarssanchez** [comment]
Hi @dinhtungdu , 

Can you let me know some images used to test this? Unfortunately another one I tried gave me the same thumbnail, so I'm not sure if it actually worked or not. 

Thanks!

**Comment by ShahAaron** [comment]
Hi @oscarssanchez,

Tested this using a public image but smart cropping still does not appear to be creating the desired result

Screenshot 2020-10-14 at 17 24 34

**Comment by dinhtungdu** [comment]
@oscarssanchez you can use this [image](https://user-images.githubusercontent.com/5423135/96116423-a101a680-0f12-11eb-91b3-684a3232c81a.png). Tested on my live site:
With smart cropping enabled:
image

With smart cropping disabled:
image


@ShahAaron Can you check the ClassifAI > Image Processing to see if smart cropping is enable?

**Comment by ShahAaron** [comment]
@dinhtungdu yes I can confirm that under ClassifAI > Image Processing smart cropping is enable

**Comment by ShahAaron** [comment]
@dinhtungdu this has now been checked by use both on a remote server and crops as expected

**Pull request merged**
