### PR TITLE
Exclude vendor library and POT file

### LINKED ISSUE #64: Build/release: Do not commit vendor library or POT file
Now that we are using a GitHub Action to handle publishing a production version into `stable` (see #62), we can also have the workflow do `composer install` and `npm run makepot` instead of dealing with that manually. Since there's a `composer.lock` file I don't think there should be any issues with the updater library being a different version in the release than whatever has been tested locally but that needs to be tested carefully.

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change
Remove pot file and vendor library from git. Update the release workflow to build the language file and install composer packages on release.

### Alternate Designs
N/A

### Benefits
Cleaner code base.

### Possible Drawbacks
N/A

### Verification Process
Check the stable branch after running updated release workflow to see language file and `plugin-update-checker` library.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues
Fixes #64 

### Changelog Entry
N/A

### CODE REVIEW

**Comment by jeffpaul** [comment]
We may want to look at bumping the update checker to its latest v4.10 as well as possibly leveraging https://github.com/Automattic/jetpack-autoloader to help with conflicts with other plugins using the same update checker but different version (e.g., https://github.com/10up/10up-experience).  Punting this to `1.7.0` to allow for more time to work on this while we in parallel work to releasing `1.6.0`.

**Comment by jeffpaul** [comment]
Note that this will likely mean updates to the [release instructions in CONTRIBUTING.md](https://github.com/10up/classifai/blob/develop/CONTRIBUTING.md#release-instructions) as well the [1.7.0 release issue steps](https://github.com/10up/classifai/issues/289).

**Review by iamdharmesh — DISMISSED** [review]
LGTM! Thanks for the PR @dinhtungdu

**Comment by dinhtungdu** [comment]
> Note that this will likely mean updates to the [release instructions in CONTRIBUTING.md](https://github.com/10up/classifai/blob/develop/CONTRIBUTING.md?rgh-link-date=2021-07-07T19%3A17%3A50Z#release-instructions) as well the https://github.com/10up/classifai/issues/289.


@jeffpaul I updated the release instruction per your suggestion.

**Pull request merged**
