### PR TITLE
Improve composer.json

### PR DESCRIPTION
**Pull request by christianc1**
### Improve composer.json

This pull request makes two changes to the composer.json file.

The first adds the `type` attribute, which designates this as WordPress plugin to ease the process for adding this as a dependency to a WordPress installation as a composer package. [More info here.](https://getcomposer.org/doc/04-schema.md#type)

The second adds the `license` attribute to the composer.json file.  Without this present, the composer.json file is not technically valid, as demonstrated by running `composer validate`. [More info here.](https://getcomposer.org/doc/04-schema.md#license)

### Benefits

Valid composer.json that a WordPress site can add/manage via Composer.

### Verification Process

`composer validate`

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/classifai-for-wordpress/blob/develop/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues
#56

### CODE REVIEW

**Comment by helen** [comment]
@christianc1 Does it work to include this via Composer when the built files are not included in the repo?

**Comment by christianc1** [comment]
@helen I installed this on a site that's still on Classic Editor.  Looks like the dist js is for Gutenberg, so I didn't even realize.  We can probably hold while we figure out if we want to support Composer based installs.  Thinking about how we distribute this, does it might make sense regardless to have build files in the repository?

**Comment by helen** [comment]
Sorry, I completely lost track of this! So the production-ready version of this plugin, like Distributor, lives in the `stable` branch. If we keep the `composer.json` file in there, would that be good enough?

**Comment by christianc1** [comment]
Works for me @helen

**Pull request merged**
