### PR TITLE
[WIP] Create Azure/Language provider and connect it to LP Service

### LINKED ISSUE #159: Auto-populate missing meta tags and descriptions
**Is your enhancement related to a problem? Please describe.**
For publishers with a high volume of posts created, it's easy to neglect meta tags and descriptions.  We currently recommend setting a systematic fallback based on content type and title but it would be a lot better to have something contextual - ideally based on target keywords from the title and then from the content and setting rules (e.g., "no more than 60 words").  This would be a huge value add for large publishers who usually end up having to manually update meta data or utilize a sub-optimal systematic solution.

**Describe the solution you'd like**
- [x] review Azure Text Analytics API for applicability
- [ ] integrate Text Analytics (or relevant API) as additional option within Language Processing
- [ ] if not utilizing an API from Azure or Watson, create new service provider
- [ ] check to see if a post has missing meta description or title and if it does populate it with what feels like a good summary within the recommended meta field length

**Designs**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by cadic**
### Description of the Change

Adds Azure/Language provider within LanguageProcessing service

The API keys screen is in Classifai > Language Processing > Microsoft Azure.

The provider will have 2 types of requests:
1. Sync request returns the result immediately in run time. Used for [Key Phrase Extraction](https://learn.microsoft.com/en-us/rest/api/language/2022-10-01-preview/text-analysis-runtime/analyze-text?tabs=HTTP#successful-key-phrase-extraction-request) 
2. Async request sets up the job, which results to be requested later. Will be used for [Abstractive Summarization](https://learn.microsoft.com/en-us/rest/api/language/2022-10-01-preview/text-analysis-runtime/submit-job?tabs=HTTP#successful-submit-abstractive-summarization-task)

The API version is currently `2022-10-01-preview`.

The Abstractive Summarization feature is not available publicly and needs to be [applied for](https://aka.ms/applyforgatedsummarizationfeatures) before we proceed with it.

Closes #159

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by jeffpaul** [comment]
@cadic might be good to possibly build off the work @dkotter has in his OpenAI/ChatGPT PR to add this functionality and focus more on ensuring someone can select either OpenAI or Azure for this feature.

**Comment by jeffpaul** [comment]
FYI that I would still like to see this get out of WIP as this would be a good UX experiment for how we handle the same functionality within the plugin via two different service providers.  I might be more pressed to handle this when we have a specific request to have a different service provider for this functionality, it may be best to leave as WIP for now.

In discussion with @dkotter, it may also be better holding on this PR until Azure brings this feature out of beta preview into general public availability.

**Comment by jeffpaul** [comment]
@Sidsector9 this might be a good PR to pick up (or perhaps close and open a subsequent related one) to use as an example of adding a new service provider with the v3 release; thoughts?

**Comment by Sidsector9** [comment]
Since we're adding this to core, it would be a good example for internal developers only. Third-party devs will still need to use hooks that will ship out with v3.

**Comment by jeffpaul** [comment]
@Sidsector9 sorry, I had intended for this to be built post-v3 stabilizing in `develop` (or even released) so that the PR here (or one like it if we want to start anew) could be an example of how to extend ClassifAI post-v3's hooks being available.

**Comment by Sidsector9** [comment]
Closing in favor of PR #786

**Pull request closed without merging**
