### PR TITLE
Add `WP-CLI` command to bulk process audio transcriptions

### LINKED ISSUE #498: Add `WP-CLI` command to bulk transcribe audio files
### Is your enhancement related to a problem? Please describe.

In #451 we added the ability to transcribe audio files using OpenAI's Whisper API. This feature fires whenever an audio file is first uploaded or can be triggered on existing individual audio files or by selecting multiple audio files. We should look to add a `WP-CLI` command that can be used to do this processing in bulk.

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dkotter**
### Description of the Change

In #451 we added the ability to generate a transcription from an audio file. This PR is a follow-up to that and adds a `WP-CLI` command that can be used to do the same thing. This is perfect for processing a large amount of audio files or having more control over which files are processed.

The new command looks like:
```
wp classifai transcribe_audio
```

and has the following options:

- A comma-delimited list of attachment IDs to process
- A `per_page` argument. This controls how many items we process in each batch. Defaults to 100. As an example, if you have 1000 items to process, all of these will be processed but will be done in batches of 100 for performance reasons
- A `force` argument that defaults to `false`. Will only process items that don't have data saved in `post_content` if set to `false` (basically won't re-process items that already have a transcription saved)
- A `dry-run` argument that defaults to `true`. You must pass `false` to actually run the command

Here are some example commands that can be run:
```
wp classifai transcribe_audio 1,2,3 --dry-run=false
```

```
wp classifai transcribe_audio --dry-run=false
```

```
wp classifai transcribe_audio --per_page=5 --force=true --dry-run=false
```

Closes #498 

### How to test the Change

Try running some of the `WP-CLI` commands as described above and ensure they all work as expected

### Changelog Entry

> Added - Custom `WP-CLI` command that can be used to generate audio transcriptions in bulk 

### Credits

Props @dkotter

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by Sidsector9** [comment]
@dkotter there are some conflicts in this PR.

**Comment by dkotter** [comment]
@Sidsector9 Thanks for pointing that out. Those should be cleaned up now

**Review by Sidsector9 — CHANGES_REQUESTED** [review]
The code looks good 👍 

These are the points I noted:

#### 1. Logs both `error` and `success` messages

Screenshot 2023-07-11 at 12 58 23 PM

1. Disable `Generate transcripts from audio files`.
2. Run `wp classifai transcribe_audio <audio_id>`.

#### 2. Logging types can be changed

- `\WP_CLI::log( sprintf( '%d items had errors', $errors ) );` can use `\WP_CLI::error()` instead.
- `\WP_CLI::success( sprintf( '%d items would have had transcriptions added', $count ) );` can use `\WP_CLI::log()` instead.


#### 3. Minor inconsistency between CLI and GUI

When `Generate transcripts from audio files` is disabled, the `Re-Transcribe` button is not rendered, however, we can still use CLI to Re-Transcribe. The setting description says
**Automatically generate transcripts for supported audio files**, but Re-Transcribing is a manual process. So IMO we should render that button at all times, whether this setting is enabled or disabled.

Adding to that, we should add a separate setting to enable/disable the feature, and use this setting value as a conditional to decide whether to render the button in the GUI.

Let me know your thoughts on this.

**Comment by dkotter** [comment]
@Sidsector9 I've updated the log types you've mentioned.

> When Generate transcripts from audio files is disabled, the Re-Transcribe button is not rendered, however, we can still use CLI to Re-Transcribe. The setting description says
> Automatically generate transcripts for supported audio files, but Re-Transcribing is a manual process. So IMO we should render that button at all times, whether this setting is enabled or disabled.
> 
> Adding to that, we should add a separate setting to enable/disable the feature, and use this setting value as a conditional to decide whether to render the button in the GUI.

I think these are both good points though I wouldn't tackle them as part of this PR. I'd suggest opening a new issue to track those things and we can look to address those in a separate PR.

**Comment by dkotter** [comment]
@Sidsector9 Let me know if you have any thoughts on the above. Hoping to get this finished off so I can proceed with a 2.2.3 release. Thanks!

**Review by Sidsector9 — APPROVED** [review]

**Pull request merged**
