### PR TITLE
Enhancement/266 A filter to manipulate the post statuses when classifying with Watson

### LINKED ISSUE #266: Add filter for processing on alternate post status
**Is your enhancement related to a problem? Please describe.**

We're using Watson language processing as an element in classifying whether or not a document is sufficiently topical to be published. For this to be effective, we want to run processing on posts prior to publishing them. 

**Describe the solution you'd like**

In https://github.com/10up/classifai/blob/51584310501073b7fb008139d2922e75b2fda50c/includes/Classifai/Command/ClassifaiCommand.php add a filter on post statuses to allow classification to run in contexts other than published posts. 

**Designs**

**Describe alternatives you've considered**

Alternate: Operate Watson on a private post type and switch post types if classification meets established criteria. Would prefer to us post status, however. 

**Additional context**

### PR DESCRIPTION
**Pull request by faisal-alvi**
### Description of the Change

This PR introduces a filter to manipulate the post statuses of posts need to be classified with Watson.

Closes #266.

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

> Added - A filter to manipulate post statuses to classify with Watson

### Credits

Props @

### CODE REVIEW

**Comment by dkotter** [comment]
@faisal-alvi Code looks fine here but I guess I'm a little confused on the actual request. The original issue mentions they want to classify things prior to publish to be help determine what content should be published.

I think this is a fine request but the file they pointed to (and where we made the change) is in our WP-CLI command. This code will not fire as part of the normal publication process in WordPress, it will have to be manually run. If we do want the change here, I'd suggest instead of a filter we just add `post_status` as a supported argument to our WP-CLI command (like we already support with `post_type`).

But probably worth clarifying with the original reporter on if this is what they really want (changes to the WP-CLI command). Seems to me we'd want to support other post statuses other than `publish` when items are actually being saved in the admin, not through manually triggering a WP-CLI command. But I may not fully understand their current workflow, which I think would be helpful to understand.

**Comment by jeffpaul** [comment]
@joedolson thoughts on the above?

**Comment by joedolson** [comment]
Thanks, @jeffpaul - My use case does need usage within the admin. The use case is that items are submitted into WP posts via REST API in unpublished statuses, run through ClassifAI language processing, then reviewed by moderators to determine whether they meet expectations for publication. The ClassifAI processing is part of the processing for identifying the editor responsible for review, so it needs to happen before publishing.

**Comment by jeffpaul** [comment]
@joedolson would the filter for `post_status` as Darin noted work for you or would an alternate approach be a more ideal implementation?

**Comment by joedolson** [comment]
As long as the filter doesn't depend on WP CLI, it should work. It looks like the current code at https://github.com/10up/classifai/blob/97541047ac827e4ac14308b69c2890c116b06348/includes/Classifai/Admin/SavePostHandler.php#L78 would meet my needs. 

That filter comment is wrong, though; that filter is new, not since 1.0.0.

**Comment by dkotter** [comment]
@joedolson @jeffpaul That filter was added in #310, which has not been released yet (we will need to update the `@since` comments once released). But I do think that solves the reported issue here and we can probably close this PR out

**Pull request closed without merging**
