### PR TITLE
Add: WPAcceptance test cases

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change

This PR:

- Updates WP version of the testing snapshot to latest.
- Add `nightly` snapshot to test against the development version of WP.
- Adds more test cases to verify plugin functionalities.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues
#205

### CODE REVIEW

**Comment by jeffpaul** [comment]
@dinhtungdu let's bump the snapshot to WordPress 5.5 to cover that core upgrade coming this week

**Comment by jeffpaul** [comment]
- [x] switch to using GitHub Actions
- [x] add daily cron

**Comment by helen** [comment]
Next steps: @dinhtungdu will be switching to GitHub Actions as the runner and setting up an additional daily cron run (especially useful for nightlies).

**Comment by dinhtungdu** [comment]
I switched PHPUnit and WPAcceptance tests to GitHub Actions. Daily cron is set up as well. WPAcceptance test is failing because WPsnapshots has a bug with `nightly` version which is addressed here: https://github.com/10up/wpsnapshots/pull/78.

**Comment by jeffpaul** [comment]
@dinhtungdu maybe we revert the `nightly` part in here so this PR can get merged in and add that back in once it's available in WP Snapshots?

**Comment by dinhtungdu** [comment]
@jeffpaul Update and GH actions are passing now. This is ready to be merged.

**Pull request merged**
