### PR TITLE
Use get_asset_info to get dependencies and version of script file for wp_enqueue_script function

### LINKED ISSUE #607: Update enqueuing of assets to use our `get_asset_info` function
### Is your enhancement related to a problem? Please describe.

As mentioned [here](https://github.com/10up/classifai/pull/602#discussion_r1370485286), we have some assets that we enqueue that use the `CLASSIFAI_PLUGIN_VERSION` constant. This was in place prior to us introducing the `get_asset_info` function. I believe we can update all of these to use that new function, which pulls the version number from the generated built files.

In looking across the codebase, here's the places I see that need updating:

- [x] `includes/Classifai/Blocks.php` line 51
- [x] `includes/Classifai/Plugin.php` line 168
- [x] `includes/Classifai/Providers/Azure/TextToSpeech.php` line 106
- [x] `includes/Classifai/Providers/OpenAI/ChatGPT.php` lines 251, 280, 310, <s>343</s>
- [x] `includes/Classifai/Providers/OpenAI/DallE.php` line 103
- [x] `includes/Classifai/Providers/Watson/NLU.php` line 244

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ravinderk**
### Description of the Change

I use `get_asset_info` function to get dependencies and version of script for `wp_enqeueue_script`.

Closes https://github.com/10up/classifai/issues/607

### How to test the Change

- [ ] All edited script files should load correctly.
- [ ] We are using `get_asset_info` function in each `wp_enqueue_script`

### Changelog Entry

> Changed - Use `get_asset_info` to get dependencies and version of script file for the `wp_enqueue_script` function.

### Credits

Props @ravinderk @dkotter, @berkod 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by dkotter** [comment]
This looks good but seems to only make this change for JS files. I think we want to do the same for the CSS files we are loading which should be referenced in the [issue description](https://github.com/10up/classifai/issues/607).

**Comment by ravinderk** [comment]
> This looks good but seems to only make this change for JS files. I think we want to do the same for the CSS files we are loading which should be referenced in the [issue description](https://github.com/10up/classifai/issues/607).

@dkotter I was not sure whether we should use the asset file version for the style file. I will implement it.

**Comment by ravinderk** [comment]
@dkotter pull request is ready to review.

**Review by dkotter — APPROVED** [review]

**Review by berkod — APPROVED** [review]

**Review by jeffpaul — APPROVED** [review]
Noting that this was reviewed in UAT today and approved for merge, but could hold off on merging until #602 gets merged in

**Pull request merged**
